"""add team_name to competition_pairs

Revision ID: a5ea0bd7d3ff
Revises: b11eb0fc4ef0
Create Date: 2026-05-09 22:00:07.132941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a5ea0bd7d3ff'
down_revision = 'b11eb0fc4ef0'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    cols = [c['name'] for c in inspect(bind).get_columns('competition_pairs')]
    if 'team_name' in cols:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_pairs', schema=None) as batch_op:
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###
