"""add competition pairs

Revision ID: b11eb0fc4ef0
Revises: 412a933af230
Create Date: 2026-05-09 21:43:09.150944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11eb0fc4ef0'
down_revision = '412a933af230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['player_a_id'], ['competition_players.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['competition_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'player_a_id', name='uq_competition_pair_a'),
    sa.UniqueConstraint('competition_id', 'player_b_id', name='uq_competition_pair_b')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competition_pairs')
    # ### end Alembic commands ###
